
import { StandardMapping } from './types';

export const DEPARTMENTS = {
  TH: [
    'ภาษาไทย', 'คณิตศาสตร์', 'วิทยาศาสตร์และเทคโนโลยี', 
    'สังคมศึกษา ศาสนาและวัฒนธรรม', 'สุขศึกษาและพลศึกษา', 
    'ศิลปะ', 'การงานอาชีพ', 'ภาษาต่างประเทศ', 'บุคลากรสำนักงาน'
  ],
  EN: [
    'Thai Language', 'Mathematics', 'Science and Technology',
    'Social Studies, Religion and Culture', 'Health and Physical Education',
    'Arts', 'Occupations and Technology', 'Foreign Languages', 'Office Staff'
  ]
};

export const PREFIXES = {
  TH: ['นาย', 'นาง', 'นางสาว'],
  EN: ['Mr.', 'Mrs.', 'Ms.']
};

export const LEVELS = [
  'ป.1/P1', 'ป.2/P2', 'ป.3/P3', 'ป.4/P4', 'ป.5/P5', 'ป.6/P6',
  'ม.1/M1', 'ม.2/M2', 'ม.3/M3', 'ม.4/M4', 'ม.5/M5', 'ม.6/M6'
];

export const STANDARDS: StandardMapping[] = [
  { 
    id: '2.4', 
    standard: 2, 
    group: 1,
    label: 'ตัวชี้วัดที่ ๒.๔ : แผนงานและการดำเนินงานด้านการพัฒนาครูและบุคลากรทางการศึกษา (พัฒนาความรู้ ทักษะวิชาชีพ)', 
    labelEn: 'Indicator 2.4: Professional Development and Training Plans for Teachers and Staff', 
    description: 'การอบรมทุกประเภทเพื่อพัฒนาทักษะวิชาชีพ',
    details: 'ตัวชี้วัดนี้ระบุชัดเจนว่าสถานศึกษาต้องมีการดำเนินงานตามแผนงานในการ "พัฒนาความรู้ ทักษะวิชาชีพ" ของครู',
    detailsEn: 'This indicator specifies that the educational institution must implement plans for "developing knowledge and professional skills" of teachers.',
    application: 'เกียรติบัตรจากการอบรมทุกประเภท ใช้ยืนยันว่าครูได้รับการพัฒนาตามเป้าหมาย (เช่น ครบ ๒๐ ชั่วโมง/ปี ตามที่โรงเรียนกำหนด) หรือพัฒนาทักษะเพื่อให้เกิดความก้าวหน้าทางวิชาชีพ',
    applicationEn: 'Certificates from all types of training confirm that teachers are developed according to goals (e.g., 20 hrs/year) or to achieve professional advancement.',
    evidence: 'รายงานการประเมินตนเองของครู (SAR ครู), แฟ้มสะสมผลงาน (Portfolio) ที่รวบรวมเกียรติบัตร',
    evidenceEn: 'Teacher Self-Assessment Report (Teacher SAR), Portfolio collecting various certificates.'
  },
  { 
    id: '2.6', 
    standard: 2, 
    group: 1,
    label: 'ตัวชี้วัดที่ ๒.๖ : การใช้สื่อ อุปกรณ์ ระบบเทคโนโลยีเพื่อสนับสนุนการจัดการศึกษา (ICT / AI / สื่อดิจิทัล)', 
    labelEn: 'Indicator 2.6: Use of Media, Equipment, and Technology Systems for Educational Support', 
    description: 'การอบรมเกี่ยวกับเทคโนโลยีและสื่อการสอน',
    details: 'หากเป็นการอบรมเกี่ยวกับ "เทคโนโลยี, ICT, AI หรือการผลิตสื่อดิจิทัล" จะตอบโจทย์ข้อนี้โดยตรง เพราะเกณฑ์ระบุเรื่องการ "ส่งเสริมการพัฒนาตนเองของครู... ให้ใช้สื่อ อุปกรณ์อย่างเหมาะสม"',
    detailsEn: 'Training on Technology, ICT, AI, or digital media production directly addresses this as criteria specify "promoting teacher self-development... to use media and equipment appropriately."',
    application: 'ใช้เป็นหลักฐานการพัฒนาสื่อการเรียนรู้ยุคใหม่',
    applicationEn: 'Used as evidence for modernizing teaching media and tools.',
    evidence: 'เกียรติบัตรอบรม ICT / AI / การผลิตสื่อ',
    evidenceEn: 'ICT / AI / Media Production Training Certificates.'
  },
  { 
    id: '3.1', 
    standard: 3, 
    group: 2,
    label: 'ตัวชี้วัดที่ ๓.๑ : การออกแบบหลักสูตรและแผนการจัดการเรียนรู้ (รางวัลแผนการสอน / พัฒนาหลักสูตร)', 
    labelEn: 'Indicator 3.1: Curriculum Design and Lesson Planning', 
    description: 'รางวัลการประกวดแผนหรือนวัตกรรมหลักสูตร',
    details: 'หากได้รับรางวัลเกี่ยวกับการ "ประกวดแผนการสอน" หรือ "การพัฒนาหลักสูตรท้องถิ่น"',
    detailsEn: 'Applicable if awards are received for "Lesson Plan Competition" or "Local Curriculum Development."',
    application: 'ใช้เป็นหลักฐานแสดงว่าเป็นแบบอย่างที่ดี (Best Practice) ในด้านการออกแบบการเรียนรู้',
    applicationEn: 'Used as evidence of Best Practice in learning design and planning.',
    evidence: 'แผนการสอนดีเด่น, เกียรติบัตรประกวดนวัตกรรมหลักสูตร',
    evidenceEn: 'Outstanding Lesson Plans, Curriculum Innovation Contest Certificates.'
  },
  { 
    id: '3.2', 
    standard: 3, 
    group: 2,
    label: 'ตัวชี้วัดที่ ๓.๒ : การจัดกิจกรรมการเรียนรู้ที่เสริมสร้างสมรรถนะ (รางวัลครูดีเด่น / Active Learning / ฝึกซ้อมนักเรียน)', 
    labelEn: 'Indicator 3.2: Learning Management that Enhances Competencies', 
    description: 'รางวัลครูผู้สอน / รางวัลจากการแข่งขันนักเรียน',
    details: 'นี่คือจุดที่ใช้เกียรติบัตรเยอะที่สุด เช่น "รางวัลครูผู้สอนดีเด่น", "รางวัลเทคนิคการสอน Active Learning", หรือ "เกียรติบัตรครูผู้ฝึกซ้อมนักเรียนชนะเลิศงานศิลปหัตถกรรม" (แสดงถึงผลลัพธ์ของการจัดกิจกรรม)',
    detailsEn: 'This is the most common category for certificates, e.g., "Outstanding Teacher Award", "Active Learning Techniques", or "Student Coaching Awards" (reflecting learning outcomes).',
    application: 'ใช้ยืนยันว่าครูจัดกิจกรรมการเรียนรู้ได้คุณภาพสูง จนเป็นแบบอย่างที่ดี (Best Practice) ได้',
    applicationEn: 'Confirms that the teacher organizes high-quality learning activities as a Best Practice.',
    evidence: 'รางวัลครูผู้สอน, เกียรติบัตรผู้ฝึกซ้อมนักเรียน',
    evidenceEn: 'Teaching Awards, Student Coaching/Mentoring Certificates.'
  },
  { 
    id: '3.3', 
    standard: 3, 
    group: 2,
    label: 'ตัวชี้วัดที่ ๓.๓ : ครูวัดและประเมินผลการเรียนรู้ของผู้เรียน (วิจัยในชั้นเรียน / นวัตกรรมการวัดผล)', 
    labelEn: 'Indicator 3.3: Measurement and Evaluation of Learner Achievement', 
    description: 'รางวัลวิจัยหรือนวัตกรรมการวัดประเมินผล',
    details: 'หากได้รับรางวัลเกี่ยวกับ "การวิจัยในชั้นเรียน (Classroom Action Research)" หรือ "นวัตกรรมการวัดประเมินผล"',
    detailsEn: 'Awards for "Classroom Action Research" or "Innovation in Measurement and Evaluation."',
    application: 'ใช้ยืนยันกระบวนการวัดผลที่เป็นระบบและต่อเนื่อง',
    applicationEn: 'Confirms systematic and continuous evaluation processes.',
    evidence: 'รายงานวิจัยในชั้นเรียน, เกียรติบัตรนวัตกรรมการประเมินผล',
    evidenceEn: 'Classroom Research Reports, Evaluation Innovation Certificates.'
  },
];

export const SCHOOL_NAME = 'โรงเรียนสาธิตอุดมศึกษา';
export const SCHOOL_ADDRESS = 'ต.หนองปรือ อ.บางละมุง จ.ชลบุรี 20150';
export const ACADEMIC_YEAR = '2568';

export const TRANSLATIONS = {
  TH: {
    systemTitle: 'ระบบจัดเก็บเกียรติบัตร SAR',
    academicYearLabel: 'ปีการศึกษา',
    teacherRole: 'ครู/บุคลากร (ส่งข้อมูล)',
    adminRole: 'ผู้บริหาร/งานประกัน (Admin)',
    welcome: 'ยินดีต้อนรับ',
    logout: 'ออกจากระบบ',
    formTitle: 'แบบฟอร์มส่งข้อมูลผลงาน/เกียรติบัตร',
    formSubtitle: 'กรุณากรอกข้อมูลให้ครบถ้วนเพื่อใช้ประกอบรายงาน SAR',
    personalInfo: 'ข้อมูลส่วนตัว',
    prefix: 'คำนำหน้า',
    fullName: 'ชื่อ-นามสกุล',
    position: 'ตำแหน่ง',
    department: 'กลุ่มสาระ / ฝ่ายงาน',
    teachingLevel: 'ระดับชั้นที่สอน (เลือกได้มากกว่า 1)',
    achievementInfo: 'ข้อมูลเกียรติบัตร / ผลงาน',
    activityName: 'ชื่อผลงาน / กิจกรรม / รางวัล',
    type: 'ประเภทผลงาน',
    level: 'ระดับผลงาน',
    organization: 'หน่วยงานที่จัด / มอบเกียรติบัตร',
    startDate: 'วันที่เริ่มกิจกรรม',
    endDate: 'วันที่สิ้นสุดกิจกรรม',
    datePlaceholder: 'วว/ดด/ปปปป',
    singleDayEvent: 'กิจกรรมวันเดียว',
    today: 'วันนี้',
    yesterday: 'เมื่อวาน',
    sameAsStart: 'วันเดียวกัน',
    standardsLink: 'การเชื่อมโยงตัวชี้วัดมาตรฐานการศึกษา',
    stdGroup1: 'มาตรฐานที่ ๒ : การพัฒนาคุณภาพการบริหารจัดการสถานศึกษา',
    stdGroup2: 'มาตรฐานที่ ๓ : การพัฒนาคุณภาพการจัดการเรียนรู้',
    attachment: 'แนบไฟล์เกียรติบัตร (JPEG เท่านั้น)',
    upload: 'อัปโหลดไฟล์',
    orDrag: 'หรือลากไฟล์มาวาง',
    clear: 'ล้างข้อมูล',
    submit: 'ส่งข้อมูล',
    uploading: 'กำลังอัปโหลด...',
    success: 'ส่งข้อมูลสำเร็จ!',
    successSubtitle: 'ข้อมูลของท่านถูกส่งไปยังฝ่ายประกันคุณภาพการศึกษาแล้ว',
    sendMore: 'ส่งข้อมูลเพิ่ม',
    adminLogin: 'เข้าสู่ระบบ Admin',
    username: 'ชื่อผู้ใช้',
    password: 'รหัสผ่าน',
    login: 'ยืนยันตัวตน',
    entryList: 'รายการเกียรติบัตร',
    all: 'ทั้งหมด',
    pending: 'รอดำเนินการ',
    approved: 'อนุมัติแล้ว',
    filterByStandard: 'ออกรายงานแยกตามมาตรฐาน',
    printReport: 'พิมพ์รายงาน',
    downloadPDF: 'ดาวน์โหลด PDF',
    delete: 'ลบ',
    statusApproved: 'อนุมัติแล้ว',
    statusPending: 'กดเพื่ออนุมัติ',
    achievementData: 'ข้อมูลผลงาน',
    linkedStandards: 'ตัวชี้วัดที่เกี่ยวข้อง',
    printedOn: 'พิมพ์เมื่อ',
    reportFooter: 'ระบบสารสนเทศ SAR โรงเรียนสาธิตอุดมศึกษา',
    pageLabel: 'หน้า',
    confirmDelete: 'ยืนยันการลบข้อมูลนี้?',
    standardShort: 'มฐ.',
    searchPlaceholder: 'ค้นหาด้วยชื่อ-นามสกุล เพื่อตรวจสอบประวัติการส่ง',
    checkHistory: 'ตรวจสอบประวัติการส่งข้อมูล',
    historyFound: 'ประวัติการส่งข้อมูลของคุณ',
    noHistory: 'ไม่พบประวัติการส่งข้อมูลในชื่อนี้',
    submittedDate: 'ส่งเมื่อ',
    detailsLabel: 'รายละเอียด',
    applicationLabel: 'การนำไปใช้',
    evidenceLabel: 'หลักฐานอ้างอิง',
    types: {
      'แข่งขัน': 'แข่งขัน',
      'อบรม': 'อบรม',
      'สัมมนา': 'สัมมนา',
      'กิจกรรมพัฒนาผู้เรียน': 'กิจกรรมพัฒนาผู้เรียน',
      'นวัตกรรม': 'นวัตกรรม',
      'รางวัล': 'รางวัล'
    },
    levels: {
      'โรงเรียน': 'โรงเรียน',
      'เขต': 'เขต',
      'จังหวัด': 'จังหวัด',
      'ภาค': 'ภาค',
      'ประเทศ': 'ประเทศ'
    }
  },
  EN: {
    systemTitle: 'SAR Certificate Management System',
    academicYearLabel: 'Academic Year',
    teacherRole: 'Teachers/Staff (Submit)',
    adminRole: 'Admin/Quality Assurance',
    welcome: 'Welcome',
    logout: 'Logout',
    formTitle: 'Achievement/Certificate Form',
    formSubtitle: 'Please fill in completely for SAR report',
    personalInfo: 'Personal Information',
    prefix: 'Prefix',
    fullName: 'Full Name',
    position: 'Position',
    department: 'Department',
    teachingLevel: 'Teaching Levels',
    achievementInfo: 'Achievement Information',
    activityName: 'Project Name / Activity / Award',
    type: 'Type',
    level: 'Level',
    organization: 'Organization',
    startDate: 'Start Date',
    endDate: 'End Date',
    datePlaceholder: 'dd/mm/yyyy',
    singleDayEvent: 'Single Day',
    today: 'Today',
    yesterday: 'Yesterday',
    sameAsStart: 'Same Day',
    standardsLink: 'Educational Standards Linkage',
    stdGroup1: 'Standard 2: Educational Administration Quality Development',
    stdGroup2: 'Standard 3: Learning Management Quality Development',
    attachment: 'Certificate (JPEG Only)',
    upload: 'Upload',
    orDrag: 'or drag here',
    clear: 'Clear',
    submit: 'Submit',
    uploading: 'Uploading...',
    success: 'Submitted!',
    successSubtitle: 'Your data has been sent to the QA department.',
    sendMore: 'Add More',
    adminLogin: 'Admin Login',
    username: 'Username',
    password: 'Password',
    login: 'Login',
    entryList: 'Certificate List',
    all: 'All',
    pending: 'Pending',
    approved: 'Approved',
    filterByStandard: 'Filter by Standard',
    printReport: 'Print',
    downloadPDF: 'Download PDF',
    delete: 'Delete',
    statusApproved: 'Approved',
    statusPending: 'Approve',
    achievementData: 'Achievement Data',
    linkedStandards: 'Related Indicators',
    printedOn: 'Printed on',
    reportFooter: 'Satit Udomseuksa School SAR System',
    pageLabel: 'Page',
    confirmDelete: 'Delete this item?',
    standardShort: 'Std.',
    searchPlaceholder: 'Search by Full Name',
    checkHistory: 'Check Submission History',
    historyFound: 'Submission history',
    noHistory: 'No history found',
    submittedDate: 'Submitted',
    detailsLabel: 'Details',
    applicationLabel: 'Application',
    evidenceLabel: 'Evidence',
    types: {
      'แข่งขัน': 'Competition',
      'อบรม': 'Training',
      'สัมมนา': 'Seminar',
      'กิจกรรมพัฒนาผู้เรียน': 'Learner Development',
      'นวัตกรรม': 'Innovation',
      'รางวัล': 'Award'
    },
    levels: {
      'โรงเรียน': 'School',
      'เขต': 'District',
      'จังหวัด': 'Province',
      'ภาค': 'Region',
      'ประเทศ': 'Country'
    }
  }
};
